name: Django CI/CD Pipline

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu=latest

    services: 
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres123
          POSTGRES_DB: postgres

        ports:
          - 5432:5432
        
        options: >-
          --health-cms pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5s

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.11
      uses: actions/setp-python@v2
      with: 
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install -- upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: python manage.py migrate
      env: 
        DATABASE_URL: postgres://postgres:postgres123@localhost:5432/postgres


    - name: Run Tests
      run: python manage.py test
        env: 
          DATABASE_URL: postgres://postgres:postgres123@localhost:5432/postgres
